#!/bin/sh

#set -xae
set -xa
# #### 05/18/99 #############################
# SETUP SEAICE CONCENTRATION ANALYSIS PROCESSING CONTROL SHELL VARIABLES
# ###########################################
export PS4='$SECONDS + '
date
echo cyc is ${cyc:?}
echo envir is ${envir:?}
echo seaice_analysis_ver is ${seaice_analysis_ver:?} 
export pid=$$

export DATA=$DATAROOT/${jobid}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z
export NET=${NET:-seaice_analysis}

export SENDEMAIL=${SENDEMAIL:-YES}
#################################################
# Specify job's execution areas (directory paths)
#################################################
export EXECseaice_analysis=${EXECseaice_analysis:-$HOMEseaice_analysis/exec/}
export FIXseaice_analysis=${FIXseaice_analysis:-$HOMEseaice_analysis/fix/}
export PARMseaice_analysis=${PARMseaice_analysis:-$HOMEseaice_analysis/parm/}
export USHseaice_analysis=${USHseaice_analysis:-$HOMEseaice_analysis/ush/}

#########################################
# Run setpdy and initialize PDY variables
#########################################
setpdy.sh
. ./PDY

echo zzzzzzzzzzzzzzzzzzz Beginning real work of seaice_analysis script zzzzzzzzzzzzzzzzzzzzzzzzz
export RUN=${RUN:-seaice_analysis}
#export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${seaice_analysis_ver})/${RUN}.${PDY}}
#export COMINm1=${COMINm1:-$(compath.py ${envir}/com/${NET}/${seaice_analysis_ver})/${RUN}.${PDYm1}}
#export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${seaice_analysis_ver})/${RUN}.${PDY}}

# manual runs:
export COMIN=${COMIN:-$HOME/noscrub/com/${NET}/${seaice_analysis_ver}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-$HOME/noscrub/com/${NET}/${seaice_analysis_ver}/${RUN}.${PDYm1}}
export COMOUT=${COMOUT:-$HOME/noscrub/com/${NET}/${seaice_analysis_ver}/${RUN}.${PDY}}

export COMOUTwmo=${COMOUTwmo:-${COMOUT}/wmo}

#export COMINsst_base=${COMINsst_base:-$(compath.py ${envir}/com/nsst/${nsst_ver}/nsst)}
export COMINsst_base=${COMINsst_base:-$(compath.py prod/com/nsst/${nsst_ver}/nsst)}
export COMINsst=${COMINsst:-${COMINsst_base}.${PDY}}
export COMINsstm1=${COMINsstm1:-${COMINsst_base}.${PDYm1}}

#export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/${envir}/dcom}
export DCOM=${DCOM:-$DCOMROOT/$PDY}
export DCOMm1=${DCOMm1:-$DCOMROOT/$PDYm1}

#NCO request for this var to be defined in J
#export HOMEobsproc_dump=${HOMEobsproc_dump:-$NWROOT/obsproc_dump.${obsproc_dump_ver}}
#export USHobsproc_dump=${USHobsproc_dump:-${HOMEobsproc_dump}/ush}
#export HOMEobsproc_shared_bufr_dumplist=${HOMEobsproc_shared_bufr_dumplist:-$NWROOT/obsproc_shared/bufr_dumplist.${obsproc_shared_bufr_dumplist_ver}}

mkdir -p $COMOUT $COMOUTwmo
env

#####################################
# Execute the script

$HOMEseaice_analysis/scripts/abbrev_analysis.sh >> $pgmout
export err=$?
err_chk
#####################################

cat $pgmout

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
