#!/bin/sh

########################################
# Generates GEMPAK grids for NCEP sea-ice analysis
# Modified 11/19/01 J.L.Partain/MPC to add VG file creation of ice edge
# Modified 12/12/04 J. Carr/PMB to move processing into production from OPC
# Modified 03/12/13 C. Caruso Magee/PMB for WCOSS. Changing 
#    /com/mrf/prod/mrf.PDY to /com/omb/prod/sice.PDY to reflect new 
#    location of engice input file.
########################################

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
export pid=$$
export DATA=$DATAROOT/${jobid}
mkdir -p $DATA
cd $DATA 

export pgmout="OUTPUT.$$"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export NET=${NET:-seaice_analysis}
export RUN=${RUN:-seaice_analysis}
export RUN2=${RUN2:-sice}
export fend=00
export finc=12
export fstart=00
export model=eng
export GRIB=
export EXT=""
export DBN_ALERT_TYPE=ICE_GEMPAK

setpdy.sh
. ./PDY
env

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${seaice_analysis_ver})/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${seaice_analysis_ver})/${RUN}.${PDY}/gempak}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

cp ${HOMEseaice_analysis}/fix/*.tbl .

########################################################
# Execute the script.
$HOMEseaice_analysis/scripts/exice_nawips.sh
# Execute the META file generation scripts.
$HOMEseaice_analysis/ush/ice_edge_vgf.sh

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
