#!/bin/sh

#set -xae
set -xa
# #### 31 March 2015 ******************************
# SETUP AVHRR DATA RETRIEVAL for SEAICE CONCENTRATION ANALYSIS filter
# ###########################################
echo zzzzzzzzzzzzzzzzzz   Have Entered Filtering Script, PDY = $PDY m1 = $PDYm1

export PS4='$SECONDS + '
date
echo cyc is ${cyc:?}
echo envir is ${envir:?}
echo seaice_analysis_ver is ${seaice_analysis_ver:?} 
export pid=$$

export DATA=$DATAROOT/${jobid}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z
export NET=${NET:-seaice_analysis}

#################################################
# Specify job's execution areas (directory paths)
#################################################
export EXECseaice_analysis=${EXECseaice_analysis:-$HOMEseaice_analysis/exec/}
export FIXseaice_analysis=${FIXseaice_analysis:-$HOMEseaice_analysis/fix/}
export PARMseaice_analysis=${PARMseaice_analysis:-$HOMEseaice_analysis/parm/}
export USHseaice_analysis=${USHseaice_analysis:-$HOMEseaice_analysis/ush/}

#########################################
# Run setpdy and initialize PDY variables
#########################################
setpdy.sh
. ./PDY

echo zzzzzzzzzzzzzzzzzz   FILTER pdy = $PDY

export RUN=${RUN:-seaice_analysis}

#debug: set -xe

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${seaice_analysis_ver})/${RUN}.${PDY}}
export COMINm1=${COMINm1:-$(compath.py ${envir}/com/${NET}/${seaice_analysis_ver})/${RUN}.${PDYm1}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${seaice_analysis_ver}/${RUN}.${PDY})}

# Offline runs:
#export COMIN=${COMIN:-${HOME}/noscrub/com/${NET}/${seaice_analysis_ver}/${RUN}.${PDY}}
#export COMINm1=${COMINm1:-${HOME}/noscrub/com/${NET}/${seaice_analysis_ver}/${RUN}.${PDYm1}}
#export COMOUT=${COMOUT:-${HOME}/noscrub/com/${NET}/${seaice_analysis_ver}/${RUN}.${PDY}}

export DCOM=${DCOM:-$DCOMROOT/$PDY}

if [ ! -d $COMOUT ] ; then
  mkdir -p $COMOUT
fi
echo zzz filter environment
env
echo zzz end filter environment

#####################################
# Execute the script
echo ${HOMEseaice_analysis}
$HOMEseaice_analysis/scripts/exseaice_filter.sh >> $pgmout
export err=$?
err_chk
#####################################

cat $pgmout

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
