#!/bin/sh

# Bring the various environment-sensitive definitions out of J jobs and to here:
#NCO refers to these as 'job card' variables
if [ -z $LMOD_FAMILY_COMPILER ] ; then
  module purge
  module load envvar/1.0
  module load imagemagick/7.0.8-7
  module load prod_envir/2.0.5
  module load prod_util/2.0.9
  #Can be loaded directly -- required for additional modules
  module load intel/19.1.3.304
  module load craype/2.7.8
  module load PrgEnv-intel/8.1.0
  module load wgrib2/2.0.8
  module load w3nco/2.4.1
  module load jasper/2.0.25
  module load libpng/1.6.37
  module load zlib/1.2.11
  module load libjpeg/9c
  module load bacio/2.4.1
  module load bufr/11.5.0
  module load g2/3.4.5
  module load grib_util/1.1.1
  #module load bufr_dumplist/2.3.0
  module load bufr_dump/2.0.0
  #module load dumpjb/5.1.0
  #module load NetCDF/4.5.0
  module load netcdf/4.7.4
  #module load lsf/10.1
  module list
fi

#set -xe
set -x

export HOMEbase=/u/Robert.Grumbine/rgdev
export seaice_analysis_ver=v4.4.0
export HOMEseaice_analysis=$HOMEbase/seaice_analysis.${seaice_analysis_ver}

export MODULEPATH_ROOT=/usrx/local/prod/modulefiles

export COMINsst_base=${COMINsst_base:-$(compath.py canned/com/gfs/v16.2/sst)}

#Important that these be after compath.py
export RUN_ENVIR=not_nco
#export envir=developer
export envir=canned

export NET=omb
export RUN=sice
export cyc=${cyc:-00}
export cycle=t${cyc}z
export pid=$$
export jobid=$pid


if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ] ; then
  #NCO
  export HOMEbase=/nw${envir}
  export COMROOT=/com
  export COMINsst_base=/com/gfs/prod
  export PCOMROOT=/pcom/${envir}/mrf
else
  #developer
  export COMROOT=/u/Robert.Grumbine/noscrub/com/
  #export DATAROOT=/gpfs/dell2/ptmp/wx21rg/
  export DATAROOT=/lfs/h2/emc/ptmp/wx21rg
  export HOMEbase=/u/Robert.Grumbine/rgdev
  export jlogfile=/u/Robert.Grumbine/jlogfile
  export PCOMROOT=/u/Robert.Grumbine/noscrub/pcom/$RUN
  export SENDCOM=YES

  #export COMROOT=/u/Robert.Grumbine/noscrub/com/${NET}/${envir}
fi

########################################################
#DBN stuff
########################################################
#export DBNROOT=/nwprod/spa_util/fakedbn
#export DBNROOT=/iodprod/dbnet_siphon
#setenv("DBNETROOT","/lfs/h1/ops/prod/dbnet")
export DBNROOT=${DBNETROOT:-/lfs/h1/ops/prod/dbnet}
export DBNETROOT=${DBNETROOT:-/lfs/h1/ops/prod/dbnet}
if [ "$envir" = "prod" ] ; then
  export SENDDBN=YES
  export SENDDBN_NTC=YES
else
  if [ $envir = "para" ] ; then
    export SENDDBN=YES
    export SENDDBN_NTC=NO
    export DBN_ALERT_TYPE=TBD_PARA
  else
    export SENDDBN=NO
    export SENDDBN_NTC=NO
  fi
fi
########################################################
